### ISSUE TITLE
Passing and int (or list) of ints into Atmosphere() produces different values as opposed to passing floats

### ISSUE THREAD

**Issue by aaronjrenfroe** [airinnova/ambiance#1]
Atmosphere(10000).temperature outputs ~289.02
Atmosphere(10000.0).temperature outputs ~223.25 < correct

Suggested fix is to add the optional param "dtype=float" to line 50 in the _parse_height function.
`        if isinstance(self.h, (int, float, list, tuple)):
             self._h = np.asarray(self.h, dtype=float)
`

**Comment by aarondettmann** [comment]
Thank you for reporting this. Unfortunately, I was not able to reproduce this on my system.

```
>>> Atmosphere(10000).temperature
array([223.25209265])
>>> Atmosphere(10000.0).temperature
array([223.25209265])
>>> Atmosphere(int(10000)).temperature
array([223.25209265])
>>> Atmosphere(np.array(10000, dtype=int)).temperature
223.25209264797857
>>> Atmosphere(np.array(10000, dtype=float)).temperature
223.25209264797857
```
According to the ICAO 7488, this should be the correct temperature (223.252 K).

I have included your suggested change as it should be more robust. I will also add some test cases for this issue later.

**Comment by aarondettmann** [comment]
Which version of `numpy` are you using?
