### ISSUE TITLE
Documentation typo in pressure equation

### ISSUE THREAD

**Issue by MartinDix** [airinnova/ambiance#12]
In the pressure equation in theory/model.rst, beta should be in the denominator of the exponent rather than in the numerator

p = p_b \left[ 1 + \frac{\beta}{T_b} (H - H_b) \right]^{-g_0/(\beta  R)} \quad \text{for} \quad \beta \neq 0

**Comment by aarondettmann** [comment]
@MartinDix - Thanks for pointing this out!
