### ISSUE TITLE
ISA+10 atmosphere

### ISSUE THREAD

**Issue by stephane-21** [airinnova/ambiance#13]
Hello,
I am trying to compute an ISA+10 atmosphere with ambiance in an "undocumented way".

I changed the constants at sea level (temperature and density), but keeping the same pressure value :
`
import ambiance
`
`
ambiance.ambiance.CONST.T_0 = 288.15+10
`
`
ambiance.ambiance.CONST.t_0 = 15+10
`
`
ambiance.ambiance.CONST.rho_0 = 1.225 * 288.15/(288.15+10)
`

But it looks like it doesn't work :
`
height_amsl = 0
`
`
ambiance.Atmosphere(height_amsl).temperature[0]  # prints 288.15
`

Is it something ambiance allows ?
Is there a good way to do that ?

Remark :
I don't even know if there is a rigorous definition of an ISA+10 atmosphere.

**Comment by MarAlder** [comment]
Did you find any solution?

**Comment by aarondettmann** [comment]
Hello @stephane-21 , I am not sure I fully understand the definitions of  ISA+10. Please feel free to refile this with some reference and use cases.

The reason why modifying some variables in the `CONST` class does not show any effect, is probably that the layer-wise properties are computed only during initialization of `CONST`. You would have to recompute these again. See:

https://github.com/airinnova/ambiance/blob/232032bbac7a8ff12e8bf9e888f6179d9094b0e9/src/ambiance/ambiance.py#L170
