### ISSUE TITLE
pressure function cannot reproduce output value

### ISSUE THREAD

**Issue by ABF-EC** [airinnova/ambiance#14]
Hi,

I am using the Ambiance module to get pressure in standard atmosphere (ICAO 1993) from a height.

If I use the exact same equations and constants as the ambiance module outside the module, I get slightly different results. I cannot figue out the reson. Can you help with this?

I am doing this :
from ambiance import Atmosphere
atmos = Atmosphere(304.8)
atmos.pressure
result is : 97716.73760077

However, if I use the equation from the pressure function like this
"""Air pressure :math:`p`"""
#H_b, T_b, beta, p_b = self._get_layer_params()
H = 304.8
H_b = 0
T_b = 288.15
beta = -0.0065
p_b = 101325.0

# Note: Pressure is computed differently for beta = 0 and for beta != 0
# Get a tensor with positions where beta is 0
beta_zero = 0
beta_zero = int(beta_zero)

beta_nonzero = 1 - beta_zero
pressure = np.zeros_like(beta)

exponent = np.divide(1, beta, out=np.zeros_like(beta), where=beta != 0)
pressue_beta_nozero = p_b*(1 + (beta/T_b)*(H - H_b))**(exponent*(-ambiance.ambiance.CONST.g_0/ambiance.ambiance.CONST.R))
pressure = pressure + pressue_beta_nozero*beta_nonzero
print(pressure) 

I get : 97716.56711902257

I do not understand where this difference is coming from, since 
print(ambiance.ambiance.CONST.LAYER_SPEC_PROP)
[[-5000.0, 320.65, -0.0065, 177687.0, 'troposphere'], [0.0, 288.15, -0.0065, 101325.0, 'troposphere'], [11000.0, 216.65, 0.0, 22632.0, 'tropopause'], [20000.0, 216.65, 0.001, 5474.87, 'stratosphere'], [32000.0, 228.65, 0.0028, 868.014, 'stratosphere'], [47000.0, 270.65, 0.0, 110.906, 'stratopause'], [51000.0, 270.65, -0.0028, 66.9384, 'mesosphere'], [71000.0, 214.65, -0.002, 3.95639, 'mesosphere'], [80000.0, 196.65, -0.002, 0.886272, 'mesosphere']]

Thus, H_b , T_b, beta = -0.0065, p_b  should be the same in your function dans my little portion of code that recycled your pressure function.

I would greatly appreciate your input about where the difference is coming from.

Best regards,

**Comment by aarondettmann** [comment]
Hi @ABF-EC! The difference is the height measure that you use. There is a distinction between the _geometric_ height above MSL (denoted `h`), and the _geopotential_ height (denoted `H`). The latter is more a mathematical construct, and usually not relevant to look at.

When you call `Atmosphere()`, you pass the geometric height as an argument, whereas internally the pressure method uses the geopotential height when computing the pressure.

You can convert between geometric and geopotential heights using conversion methods as described here:

https://ambiance.readthedocs.io/en/latest/user_guide/detailed_user_guide.html#geometric-and-geopotential-height

In your case, the difference is small, but it should explain the small difference in the pressure:

```python
>>> from ambiance import Atmosphere
>>> h = 304.8
>>> H = Atmosphere.geom2geop_height(h)
>>> H
array([304.78538587])
```

**Comment by ABF-EC** [comment]
Hi Aron,

Thank you very much for you help!

I was wondering about the equation used by Ambiance to compute the geopotential height.
Here is the equation that I have found in ICAO 1993
![image](https://github.com/user-attachments/assets/63c01825-6769-4aa5-abef-9f1d96603027)

vs the one that I have found in Ambiance
![image](https://github.com/user-attachments/assets/2fb45e03-9b76-4096-bec0-4880ed879a3c)

Have a nice day!
Anna-Belle

**Comment by aarondettmann** [comment]
Hello Anna-Belle, equation (7) is the gravitational acceleration, which decreases with altitude. It is available via the property `grav_accel`:

https://github.com/airinnova/ambiance/blob/232032bbac7a8ff12e8bf9e888f6179d9094b0e9/src/ambiance/ambiance.py#L409-L412

```python
>>> Atmosphere(0).grav_accel
array([9.80665])
```

In my reference, equation (8) is the conversion between geometric to geopotential height. This equation should correspond to the code snippet you show.

![eq_7_8](https://github.com/user-attachments/assets/b78954a5-5888-42eb-bddc-750339e4e225)

I hope this clarifies it.
Aaron

**Comment by ABF-EC** [comment]
Yes, thanks a lot Aaron! 

I appreciate you taking the time!
