### ISSUE TITLE
Need humidity support.

### ISSUE THREAD

**Issue by dlsflh** [airinnova/ambiance#3]
Please add humidity(g/kg) vs altitude function.

**Comment by aarondettmann** [comment]
Thanks for your suggestion. Specific humidity (or any other humidity measure) is not yet implemented in this package. *ambiance* is so far a representation of the ICAO 1993 atmosphere model which does not define humidity.

We could think about adding a humidity model. Do you have a paper or other reference describing such a model?

**Comment by dlsflh** [comment]
Thanks for your quick response！
In fact, I'm working in aircraft environment control system. I found a simple relationship between humidity and altitude from sea level to 50,000 ft (15 kilometers) in ARP85E(a SAE standard that we are using).
I hope it can help.
Thanks in advance.
![Snipaste](https://user-images.githubusercontent.com/14144719/79705134-294a1a80-82e7-11ea-9e1a-26b88e7b7b79.png)

**Comment by aarondettmann** [comment]
Thank you for providing a reference! I will read up on the model later. In the meantime, I just want to point out that the `Atmosphere` object can be easily extended. The easiest way to do this, is to subclass from `Atmosphere` and to add your own custom function. The example below shows how this works.

```python
from ambiance import Atmosphere

class MyExtendedAtmosphere(Atmosphere):
    @property
    def specific_humidity(self):
        return 2*self.h  # Define your own function of altitude here...

atmosphere = MyExtendedAtmosphere([0, 1, 100])
print(atmosphere.specific_humidity)
```

In the example, I have added the function `specific_humidity`. Note that by adding the decorator `@property`, you do not need to call the function using parentheses. In the example, I have just added a dummy function which multiplies the altitude by a factor of two, but you can replace it with any function you like. The variable `self.h` is the geometric altitude. So in this example, the script prints:

```python
[  0.   2. 200.]
```

**Comment by aarondettmann** [comment]
It seems I cannot access to the particular standard, ARP85(e), that you mentioned. The full document is behind a paywall for me. However, I highly encourage you to follow the suggestion above to simply extend the atmosphere model with your own custom functions. Note that I have added a section in the documentation which gives a few more hints on writing custom functions.

In particular, I noted that your model has a constant humidity level from 0 to 10000 ft, so two expressions may be needed to describe the whole model. You will find a few suggestions on how to write your own function in this case. I hope this is helpful. Let me know if anything is unclear.

* https://ambiance.readthedocs.io/en/latest/user_guide/extending.html

**Comment by aarondettmann** [comment]
I am closing this issue. Feel free to comment here or open a new issue :)

**Comment by dlsflh** [comment]
Sorry for late reply, I'm not good at programming, but i will try as you recommanded above.
Thank you.
